### ISSUE TITLE
Submodule for each template framwork

### ISSUE THREAD

**Issue by sonukuldeep** [Code-and-State/typescript-bootcamp#2]
Hey there, Seb 👋. Its me cat. I was wondering if its possible to have template frameworks in their separate repository so its easier to update and clone.  
Each framework repo is linked by submodules so the main module doesn't grow too big as more and more frameworks are added to the template.

This should fix the following issue:
- People wont have to clone the main repo in order to use their preferred framework
- I feel, managing the main repo and individual projects will become easier as all of them will be more organized

**Comment by seb-icp** [comment]
Thanks for the suggestion Cat, that's a great one. I'm in the process of reformatting the repository to make it accessible to future students. I'll take your suggestion into account 👍
